substitutions:
  device_name: meteo-station

packages:
  wifi: !include common/wifi.yaml
  device_base: !include common/device_base.yaml

esphome:
  name: ${device_name}
  friendly_name: LaskaKit Meteo Mini

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# Enable I2C power
output:
  - platform: gpio
    pin: GPIO3 
    id: my_output
    restore_mode: ALWAYS_ON  # Keep the pin high after boot

i2c:
  sda: 19
  scl: 18
  scan: true
  id: bus_a

sensor:
  - platform: bme280
    temperature:
      name: "${device_name} Temperature"
      oversampling: 16x
    pressure:
      name: "${device_name} Pressure"
    humidity:
      name: "${device_name} Humidity"
    address: 0x77
    update_interval: 60s
  - platform: adc
    # divider ratio = 1.7693877551
    pin: GPIO0
    name: "${device_name} Batery Level"
    entity_category: diagnostic   
    filters:
      - multiply: 1.7693877551
